#!/bin/bash
. common

stopall

locatetar

removeall

echo create instances
createfirst
cp -R 1 2
cp -R 1 3

echo start all instances
start 1
start 2
start 3

sleep 20

port

createindex

echo stop one data node
stop 1
sleep 5
port
status
if [ "yellow" != "${STATUS}" ]; then
	echo status error 2
	echo $STATUS
	exit 1
fi

insertdoc
sleep 2
query

echo stop data nodes
stop 2
stop 3
sleep 5

echo restart data nodes
start 1
sleep 5
start 2
sleep 10
start 3
sleep 10
port
status
echo ${STATUS}
while [ "red" == "${STATUS}" ];
do
	sleep 10
	status
	echo ${STATUS}
done

query

stopall

for NODE in $(seq 1 3);
do
	echo node $NODE
	rm -f ${NODE}/config/elasticsearch.yml
	cp 1/config/elasticsearch.yml.bak ${NODE}/config/elasticsearch.yml
	start ${NODE}
	sleep 10
	port
	status
	echo ${STATUS}
	if [ "red" == "${STATUS}" ]; then
		echo status error 3
		exit 1
	fi
	query
	stop ${NODE}
	sleep 5
done

stopall
